### ISSUE TITLE
Adicionar NINJA no id

### ISSUE THREAD

**Issue by ghost** [Mutirao/id.org.br#25]
Adicionar o midianinja.org nos serviços do id.org.br

**Comment by uira** [comment]
@BrancaSchulz @uira vai fazer oficina de criação de serviço... @jedi0  e @brancaschulz inscritos?

**Comment by uira** [comment]
![captura de tela 2018-07-04 as 19 19 39](https://user-images.githubusercontent.com/89998/42295314-4e7ad6fa-7fbf-11e8-9a25-d89e77845960.png)
